### ISSUE TITLE
Menu can be opened during a Cutscene or on top of the Interaction Menu

### ISSUE THREAD

**Issue by tomilovsenya** [Guad/NativeUI#101]
The title is self-explanatory. I heard there's no good way of determining whether a cutscene is playing or the interaction menu is active, but can't be sure.

**Comment by tomilovsenya** [comment]
![20190226145625_1](https://user-images.githubusercontent.com/37510860/53425047-21a22500-3a06-11e9-8127-f3c6d191bbbe.jpg)

Here's a screen if needed.

**Comment by justalemon** [comment]
Enabling a menu during a cutscene can be useful for some some mods.

If you really don't want to enable the menu during a cutscene, use something like `Game.Player.CanControlCharacter`.

**Comment by tomilovsenya** [comment]
Oh, yeah, I simply forgot that such native exists. But what about the collision with the Interaction Menu opened?

**Comment by justalemon** [comment]
Well, I don't know how you can avoid collisions with the interaction menu because as far as I know the same Scaleform's are used. You can't do a check with [_HAS_NAMED_SCALEFORM_MOVIE_LOADED](https://runtime.fivem.net/doc/natives/#_0x0C1C5D756FB5F337) or [HAS_SCALEFORM_MOVIE_LOADED](https://runtime.fivem.net/doc/natives/#_0x85F01B8D5B90570E).

If you really don't want the menus to open when there is a cutscene active, use [IS_CUTSCENE_ACTIVE](https://runtime.fivem.net/doc/natives/#_0x991251AFC3981F84) or [IS_CUTSCENE_PLAYING](https://runtime.fivem.net/doc/natives/#_0xD3C2E180A40F031E)

**Comment by justalemon** [comment]
This question appears to be answered. If you need more help, open another issue or reopen the existing one.
