### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Guad** [Guad/NativeUI#12]
FPS drops when menu is open.

**Comment by RainerHilmer** [comment]
I think this happens when attaching the tick event to MenuPool.ProcessMenus(). I tried setting the Interval to 100ms and faced the menu flashes all along. Even just calling Yield() after MenuPool.ProcessMenus() causes this. Why does the menu disappear in-between anyway? If that wouldn't be the case we wouldn't have those issue, I'm pretty sure.

**Comment by Guad** [comment]
That's because with the Draw() method of the menus draws the sprites and text for one frame, so you'd have to call it every frame. If you set the interval too big, it draws it every other frame, which causes the flicker.

**Comment by RainerHilmer** [comment]
Got that but isn't there any other way? I mean, the menu functionality of scripthookvdotnet doesn't have this problem. Maybe you can get an idea if you check out the source code of V1.1 and have a look at it. ;-)

**Comment by Guad** [comment]
This menu uses the same functionality, except that the old scripthookvdotnet menu was much simpler and didn't use any sprites, so it was easy on the performance.

**Comment by RainerHilmer** [comment]
How about always pausing the game at menu popup? Do you also need to redraw with each frame then?

**Comment by Guad** [comment]
Yes, it's how the game implements sprites, there's no way around that.

**Comment by ardaozkal** [comment]
directx hooking maybe? but that'd take a complete rewrite

**Comment by Guad** [comment]
@ardaozkal That'd obscure game items such as the mouse pointer and other stuff.

**Comment by E66666666** [comment]
ScriptHookV uses it's own drawTexture instead of the DRAW_SPRITE native. Would using that help?

Also, would drawing in a different thread help? Not sure if you can do this with respect to GTAs threads.

**Comment by sollaholla** [comment]
@E66666666 I also noticed shv's drawTexture lags behind a frame. Not sure if it's just me or...

**Comment by E66666666** [comment]
@Guad 
Did some measurements:  
* FPS /w no menu onscreen: 82-85FPS
* FPS /w menu onscreen: 50-55 FPS
* FPS /w menu onscreen, DisEnableControls commented out: 74-76 FPS
* FPS /w menu onscreen, input group 2 only: 65-66 FPS

Turns out the `foreach (var con in Enum.GetValues(typeof(Control)))` in [DisEnableControls](https://github.com/Guad/NativeUI/blob/898b78826171059a27a6963accb450c656beaad3/UIMenu.cs#L236) is responsible for about ~20FPS from the total ~30FPS drop when having the menu open. Not sure how you'd replace this "block everything", but removing the 0 and 1 helps a tiny bit. Only disabling a small set of controls would be even better.

Not sure where the 10 FPS drop comes from exactly, as measuring the impact of the string splittage isn't very conclusive.

**Comment by kagikn** [comment]
Actually, Tanjitsu found `Enum.GetValues` in `DisEnableControls` drops huge fps before I did.
Didn't noticed that when I made my PR, though.

**Comment by Guad** [comment]
Well shit, now it looks kinda obvious. Thanks again.
