### ISSUE TITLE
Trying to display a custom image

### ISSUE THREAD

**Issue by AAYapps** [Guad/NativeUI#16]
I have been trying to display a custom image in gta 5 with your sprite example

                        Sprite.DrawTexture(Sprite.WriteFileFromResources(Assembly.GetExecutingAssembly(), "BTTF Time Travel.amber0.pung", Application.StartupPath + "\\image.png"), new Point(0, 1), new Size(10, 10));

the game keeps crashing with

fatal: directx "path of the image" texture creation failed.

Game exits. 

GTA 5
dot net script hook 2.1
latest nativeUI

any help?

**Comment by Guad** [comment]
First of all, you shouldn't call `WriteFileFromResources` in a tick, as it will constantly write the file to disk. Instead call it once in the constructor and save the absolute path.
Second, your filename is proably wrong since the default namespace cannot contain spaces. Look in Project > BTTF Time Travel Properties...; There's a field named "Default namespace", it should be something like `BTTF_Time_Travel`, use that instead.

**Comment by AAYapps** [comment]
I made the changes, but it still crashes

The file is present in the scripts folder as image.png 

![image](https://cloud.githubusercontent.com/assets/11639974/9864877/6e247918-5b1c-11e5-8e83-6891831a66df.png)

image.pmg is there

**Comment by Guad** [comment]
Make sure image.png is not empty, and the game has permissions to open it

**Comment by AAYapps** [comment]
I ran gta 5 as admin, still crashed

**Comment by AAYapps** [comment]
I found the problem. I left out the scripts folder. LOL Thankyou for the help.
